# This file controls the behavior of Trunk: https://docs.trunk.io/cli
# To learn more about the format of this file, see https://docs.trunk.io/reference/trunk-yaml
version: 0.1
lint:
  enabled:
    - bandit
    - black
    - checkov
    - git-diff-check
    - isort 
    - osv-scanner
    - oxipng
    - prettier
    - ruff
    - trivy
    - trufflehog
  disabled:
    - markdownlint
    - svgo
  definitions:
    - name: black
      commands:
        - name: format
          run: black --skip-string-normalization -q ${target}
actions:
  disabled:
    - trunk-announce
    - trunk-check-pre-push
    - trunk-fmt-pre-commit
  enabled:
    - trunk-upgrade-available
